<?php
require_once '../vendor/autoload.php'; // Load Composer's autoloader
require_once '../include/db_conn.php'; // Include your database connection

// Retrieve search term from GET request
$searchQuery = $_GET['search'] ?? '';

// Fetch the logged-in user's information
session_start();
$staffId = $_SESSION['staff_id'] ?? 'Unknown';
$firstName = $_SESSION['first_name'] ?? 'Unknown';
$lastName = $_SESSION['last_name'] ?? '';

// Get the current date and time
$printedDate = date("Y-m-d H:i:s");

// Fetch filtered data from the database using PDO
$query = "SELECT * FROM company WHERE is_deleted = 0";
$params = [];

if (!empty($searchQuery)) {
    $query .= " AND (name LIKE :search OR location LIKE :search OR description LIKE :search)";
    $params[':search'] = "%$searchQuery%";
}

$query .= " ORDER BY name ASC"; // Order by company name alphabetically

$stmt = $conn->prepare($query);
$stmt->execute($params);
$companies = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Include TCPDF
require_once '../vendor/tecnickcom/tcpdf/tcpdf.php';

// Create PDF instance in landscape mode
$pdf = new TCPDF('L', 'mm', 'A4', true, 'UTF-8', false);
$pdf->SetCreator('Company Management System');
$pdf->SetAuthor($firstName . ' ' . $lastName);
$pdf->SetTitle('Company List Report');
$pdf->SetSubject('Company List Report');

// Remove default header/footer
$pdf->setPrintHeader(false);
$pdf->setPrintFooter(false);

// Set margins
$pdf->SetMargins(15, 15, 15);
$pdf->SetAutoPageBreak(true, 15);

// Add a page
$pdf->AddPage();

// Set colors
$headerBgColor = [52, 152, 219]; // Blue
$headerTextColor = [255, 255, 255]; // White
$alternateRowColor = [240, 248, 255]; // Light blue
$borderColor = [189, 195, 199]; // Gray

// Header
$pdf->SetFont('helvetica', 'B', 20);
$pdf->SetTextColor(44, 62, 80); // Dark text
$pdf->Cell(0, 15, 'COMPANY LIST REPORT', 0, 1, 'C');
$pdf->Ln(2);

// Report information section
$pdf->SetFont('helvetica', '', 10);
$pdf->SetTextColor(44, 62, 80);
$pdf->SetFillColor(248, 249, 250);
$pdf->SetDrawColor($borderColor[0], $borderColor[1], $borderColor[2]);

// Create a box for the report info
$pdf->SetLineWidth(0.2);
$pdf->RoundedRect(15, $pdf->GetY(), $pdf->GetPageWidth() - 30, 25, 2, '1111', 'DF', [], [248, 249, 250]);

$y = $pdf->GetY() + 5;
$pdf->SetXY(20, $y);
$pdf->SetFont('helvetica', 'B', 10);
$pdf->Cell(30, 5, 'Generated By:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 10);
$pdf->Cell(100, 5, "$firstName $lastName (ID: $staffId)", 0, 0, 'L');

$pdf->SetFont('helvetica', 'B', 10);
$pdf->Cell(30, 5, 'Date & Time:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 10);
$pdf->Cell(80, 5, $printedDate, 0, 1, 'L');

$y = $pdf->GetY() + 5;
$pdf->SetXY(20, $y);
$pdf->SetFont('helvetica', 'B', 10);
$pdf->Cell(30, 5, 'Search Filter:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 10);
$pdf->Cell(100, 5, ($searchQuery ? $searchQuery : 'None'), 0, 0, 'L');

$pdf->SetFont('helvetica', 'B', 10);
$pdf->Cell(30, 5, 'Total Companies:', 0, 0, 'L');
$pdf->SetFont('helvetica', '', 10);
$pdf->Cell(80, 5, count($companies), 0, 1, 'L');

$pdf->Ln(15);

// Table Headers
$pdf->SetFont('helvetica', 'B', 11);
$pdf->SetFillColor($headerBgColor[0], $headerBgColor[1], $headerBgColor[2]);
$pdf->SetTextColor($headerTextColor[0], $headerTextColor[1], $headerTextColor[2]);
$pdf->SetDrawColor($borderColor[0], $borderColor[1], $borderColor[2]);

// Column widths (adjusted for landscape)
$colWidths = [15, 70, 50, 120, 15];

// Table headers
$pdf->Cell($colWidths[0], 10, '#', 1, 0, 'C', true);
$pdf->Cell($colWidths[1], 10, 'Company Name', 1, 0, 'C', true);
$pdf->Cell($colWidths[2], 10, 'Location', 1, 0, 'C', true);
$pdf->Cell($colWidths[3], 10, 'Description', 1, 0, 'C', true);
$pdf->Cell($colWidths[4], 10, 'ID', 1, 1, 'C', true);

// Reset text color for table content
$pdf->SetTextColor(44, 62, 80);
$pdf->SetFont('helvetica', '', 10);

// Counter for row numbering
$counter = 1;
$fill = false;

// Loop through records and add to table
foreach ($companies as $company) {
    // Set the background color for alternating rows
    if ($fill) {
        $pdf->SetFillColor($alternateRowColor[0], $alternateRowColor[1], $alternateRowColor[2]);
    } else {
        $pdf->SetFillColor(255, 255, 255);
    }
    
    // Calculate row height based on description content
    $descriptionHeight = $pdf->getStringHeight($colWidths[3], $company['description']);
    $rowHeight = max(8, $descriptionHeight);
    
    // Save current position
    $x = $pdf->GetX();
    $y = $pdf->GetY();
    
    // Row number
    $pdf->Cell($colWidths[0], $rowHeight, $counter, 1, 0, 'C', $fill);
    
    // Company name - using MultiCell for potential long names
    $pdf->SetXY($x + $colWidths[0], $y);
    $pdf->MultiCell($colWidths[1], $rowHeight, htmlspecialchars($company['name']), 1, 'L', $fill);
    
    // Location - using MultiCell for potential long locations
    $pdf->SetXY($x + $colWidths[0] + $colWidths[1], $y);
    $pdf->MultiCell($colWidths[2], $rowHeight, htmlspecialchars($company['location']), 1, 'L', $fill);
    
    // Description (using MultiCell for text wrapping)
    $pdf->SetXY($x + $colWidths[0] + $colWidths[1] + $colWidths[2], $y);
    $pdf->MultiCell($colWidths[3], $rowHeight, htmlspecialchars($company['description']), 1, 'L', $fill);
    
    // Company ID
    $pdf->SetXY($x + $colWidths[0] + $colWidths[1] + $colWidths[2] + $colWidths[3], $y);
    $pdf->Cell($colWidths[4], $rowHeight, $company['id'], 1, 1, 'C', $fill);
    
    // Reset position for next row
    $pdf->SetX($x);
    
    // Toggle fill for next row
    $fill = !$fill;
    $counter++;
    
    // Check if we need a page break for the next row
    if ($pdf->GetY() > $pdf->getPageHeight() - 20) {
        $pdf->AddPage();
        
        // Repeat header on new page
        $pdf->SetFont('helvetica', 'B', 11);
        $pdf->SetFillColor($headerBgColor[0], $headerBgColor[1], $headerBgColor[2]);
        $pdf->SetTextColor($headerTextColor[0], $headerTextColor[1], $headerTextColor[2]);
        
        $pdf->Cell($colWidths[0], 10, '#', 1, 0, 'C', true);
        $pdf->Cell($colWidths[1], 10, 'Company Name', 1, 0, 'C', true);
        $pdf->Cell($colWidths[2], 10, 'Location', 1, 0, 'C', true);
        $pdf->Cell($colWidths[3], 10, 'Description', 1, 0, 'C', true);
        $pdf->Cell($colWidths[4], 10, 'ID', 1, 1, 'C', true);
        
        $pdf->SetTextColor(44, 62, 80);
        $pdf->SetFont('helvetica', '', 10);
    }
}

// Add footer with page numbers
$pdf->SetY(-15);
$pdf->SetFont('helvetica', 'I', 8);
$pdf->Cell(0, 10, 'Page ' . $pdf->getAliasNumPage() . ' of ' . $pdf->getAliasNbPages(), 0, 0, 'C');

// Output the PDF
ob_end_clean();
$pdf->Output('company_list_report.pdf', 'I');
?>